FROM nginx:alpine
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
RUN apk add bash git curl zip vim unzip ffmpeg

# Dockerfile (e.g., ./php/Dockerfile)
FROM php:fpm-alpine

# Install bash, ffmpeg, and process tools
RUN apk add --no-cache bash ffmpeg procps

# Optional: Set working directory
WORKDIR /IPTV

# Optional: Add non-root user if needed
# RUN adduser -D -H nginx



